/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiElevenlabsConversationTokenRouteImport } from './routes/api/elevenlabs.conversation-token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElevenlabsConversationTokenRoute =
  ApiElevenlabsConversationTokenRouteImport.update({
    id: '/api/elevenlabs/conversation-token',
    path: '/api/elevenlabs/conversation-token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/elevenlabs/conversation-token': typeof ApiElevenlabsConversationTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/elevenlabs/conversation-token': typeof ApiElevenlabsConversationTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/elevenlabs/conversation-token': typeof ApiElevenlabsConversationTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/elevenlabs/conversation-token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/elevenlabs/conversation-token'
  id: '__root__' | '/' | '/api/elevenlabs/conversation-token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiElevenlabsConversationTokenRoute: typeof ApiElevenlabsConversationTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elevenlabs/conversation-token': {
      id: '/api/elevenlabs/conversation-token'
      path: '/api/elevenlabs/conversation-token'
      fullPath: '/api/elevenlabs/conversation-token'
      preLoaderRoute: typeof ApiElevenlabsConversationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiElevenlabsConversationTokenRoute: ApiElevenlabsConversationTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
