/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiElevenlabsTokenRouteImport } from './routes/api/elevenlabs.token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElevenlabsTokenRoute = ApiElevenlabsTokenRouteImport.update({
  id: '/api/elevenlabs/token',
  path: '/api/elevenlabs/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/elevenlabs/token': typeof ApiElevenlabsTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/elevenlabs/token': typeof ApiElevenlabsTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/elevenlabs/token': typeof ApiElevenlabsTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/elevenlabs/token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/elevenlabs/token'
  id: '__root__' | '/' | '/api/elevenlabs/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiElevenlabsTokenRoute: typeof ApiElevenlabsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elevenlabs/token': {
      id: '/api/elevenlabs/token'
      path: '/api/elevenlabs/token'
      fullPath: '/api/elevenlabs/token'
      preLoaderRoute: typeof ApiElevenlabsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiElevenlabsTokenRoute: ApiElevenlabsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
